import time
import uuid
from fastapi import Request
from starlette.middleware.base import BaseHTTPMiddleware
from starlette.responses import Response

from backend.utils.custom_logger import setup_logger

logger = setup_logger("utils.tracing")


class TracingMiddleware(BaseHTTPMiddleware):
    """FastAPI Middleware to trace HTTP requests.

    Generates a unique request ID, hooks request start/end times,
    logs duration metrics, and appends the tracking value to responses.
    """

    async def dispatch(self, request: Request, call_next) -> Response:
        # Check if X-Request-ID was already generated by downstream systems (e.g. gateway/load-balancer)
        request_id = request.headers.get("X-Request-ID") or str(uuid.uuid4())
        
        # Store in request state for internal router accessibility
        request.state.request_id = request_id
        
        start_time = time.time()
        logger.info(f"[{request_id}] Incoming request: {request.method} {request.url.path}")
        
        try:
            response = await call_next(request)
        except Exception as e:
            duration = time.time() - start_time
            logger.error(
                f"[{request_id}] Request failed: {request.method} {request.url.path} "
                f"after {duration:.4f}s. Error: {e}"
            )
            raise
            
        duration = time.time() - start_time
        logger.info(
            f"[{request_id}] Completed request: {request.method} {request.url.path} "
            f"- Status: {response.status_code} - Duration: {duration:.4f}s"
        )
        
        # Attach tracing header to response
        response.headers["X-Request-ID"] = request_id
        return response
